spring.datasource.url=jdbc:postgresql://localhost:5432/shipment_db
spring.datasource.username=your_username
spring.datasource.password=your_password
jwt.secret=your_jwt_secret
stripe.secret.key=sk_test_YOUR_SECRET_KEY
stripe.webhook.secret=whsec_YOUR_WEBHOOK_SECRET
